### ISSUE TITLE
Fail to add the fourth node

### ISSUE THREAD

**Issue by Rucchao** [neunhoef/ArangoDBStarter#9]
Hi, Max,

I am failed to add the fourth node to ArangoDB cluster when I try to perform this command ./arangodb --join MasterIP, could you please help me with this?

ps: I find the saying from the readme: Size must be odd, I do have five nodes available, but how can I add the rest two nodes into the cluster.

Error log:

Cannot start because of error from master: Post MasterIP:4000/hello: dial tcp MasterIP:4000: connection refused.

Thanks.

**Comment by Rucchao** [comment]
Since nobody reply. I just come back to answer, using the old version, I set parameter agencysize in file arangodb.go to 5, and now I manage to launch a cluster with 5 agencies, but I am wondering when arango cluster will support for deploying more agencies ?

**Comment by neunhoef** [comment]
Sorry for replying only now: The size of the agency needs to be odd because of the Raft protocol we are using. However, this does not mean that one cannot have a 4 node ArangoDB cluster. In this case the first three will have an agent but the fourth will only start a coordinator and a dbserver. You simply leave --agencySize at 3 and start a 4th node pointing it to the master.
The error you got is/was either a bug or means that there were some network problems. Can you please try with the latest version in the new repository:
  https://github.com/arangodb-helper/ArangoDBStarter
Note that the default port arrangement has changed, which is described in the README.
